### ISSUE TITLE
Bug: Schedule Worker deadlocks randomly

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#143] opened 2017-11-17 09:09 UTC
We've now observed several times that the schedule worker will just silently deadlock. It does not log annything, it does not respond to _any_ signals (even SIGKILL) and this lead to severall missed recordings now. 

We've only noticed this behaviour after upgrading to Opencast 3.3 from 2.2.3. Also, we have a lot more scheduled recordings this semester, so the responses from the capture-admin endpoint take a bit longer.

This is a critical issue for us right now.

**Comment by lkiesow** [comment] 2020-06-27 12:48
Closing this since I couldn't reproduce this. Plus the internals have chenged quite a bit.
Please re-open if this happens again.

**Closed as completed by lkiesow** 2020-06-27 12:48 UTC
Labels: bug
